configurable backend with env variables
DevConfCM/devconfcm pull request #8
Opened 2022-02-25 17:34 UTC by Falence

This makes the backend configurable by setting up environment variables to avoid the hardcoding of values such as ports, keys e.t.c

2022-02-25 19:28 UTC, ivange94 requested changes
The way I'd like this implemented is that we have a `config` package that hides all the logic of reading configurations. Then a config object like

```
type Config struct {
    Host string
    Port int
}

var DefaultConfig = getConfig()

func getConfig() {
    config := Config{}
    config.Host = os.Getenv("PORT")
    config.Port = os.Getenv("Host")

    return &config
}
```
Then inside main you can do 
```
port := config.DefaultConfig.Port
router.Logger.Fatal(router.Start(port))
```

2022-02-25 21:41 UTC, Falence commented
Oh I see. This actually makes a lot of sense. Thank you.
I'll work on it

2022-02-28 15:40 UTC, Falence commented
I've modified the PR. Kindly let me know what you think.

2022-03-01 20:59 UTC, ivange94 requested changes
Looks good. Just minor changes and a recommendation to use viper for this. With viper you can provide a config.json with default environment variables. These variables can be overridden by environment variables or command line flags. `config.json` will be tracked by git and should never hold sensitive data like usernames and passwords. We'll always use env variables for those.

2022-03-01 20:59 UTC, ivange94 commented on README.md
> +Create a `.env` to house all environment variables (`PORT` e.t.c)
Document all environment variables needed.

2022-03-01 20:59 UTC, ivange94 commented on pkg/config/config.go
> +	Port string
Port should be an integer

2022-03-01 20:59 UTC, ivange94 commented on pkg/config/config.go
> +		Port: ":" + os.Getenv("PORT"),
Just `Port: os.Getenv("PORT")`

2022-03-02 07:10 UTC, Falence commented
> Looks good. Just minor changes and a recommendation to use viper for this. With viper you can provide a config.json with default environment variables. These variables can be overridden by environment variables or command line flags. `config.json` will be tracked by git and should never hold sensitive data like usernames and passwords. We'll always use env variables for those. See a quick entry to viper https://dev.to/techschoolguru/load-config-from-file-environment-variables-in-golang-with-viper-2j2d

I've modified the PR.
Thank you for this. I must say, I learnt a lot already.

2022-03-02 18:13 UTC, ivange94 requested changes
Just minor comments.

2022-03-02 18:13 UTC, ivange94 commented on app.env
> +TEST_DB=test.db
Add new line

2022-03-02 18:13 UTC, ivange94 commented on app.env
> +HOST=
If the default will be an empty string then you can just leave it out.

2022-03-02 18:13 UTC, ivange94 commented on README.md
> +For sensitive variables such as `USERNAME`, `PASSWORD` e.t.c, put them in your system's evironment variables.
Add a section for variables like this

```
### Configuration variables

* PORT: Port application will be listening to
* HOST: 
* DB_URL: Url for db
```
We don't need the `TEST_DB` config.

2022-03-02 18:13 UTC, ivange94 commented on pkg/config/config.go
> +var DefaultConfigs = getConfigs()
This should be singular `DefaultConfig`

2022-03-02 18:13 UTC, ivange94 commented on pkg/router/router.go
> +	port := ":" + strconv.Itoa(config.DefaultConfigs.Port)
This looks cleaner

```
port := config.DefaultConfigs.Port
url := fmt.Sprintf(":%v", port)
```

2022-03-02 22:17 UTC, Falence commented
Resolved!

2022-03-04 11:36 UTC, merged

2022-03-04 11:36 UTC, ivange94 commented
Thank you @Falence

2022-03-04 13:01 UTC, Falence commented
@ivange94 I'm looking forward to more tasks and more code reviews